### ISSUE TITLE
SIGSEGV: segmentation violation code=0x1

### ISSUE THREAD

**Issue by lusorio** [mnmandahalf/check-ecr-image-exists#3]
Hi,

Having troubles with the last version of this action. Any idea?

Thank you!

```
Run mnmandahalf/check-ecr-image-exists@e072d624e6b48e0798b87080a96e49869951e7a2
  with:
    region: ***
    repository-name: ***
    access-key-id: ***
    secret-access-key: ***
  env:
    AWS_DEFAULT_REGION: ***
    AWS_REGION: ***
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
/usr/bin/docker run --name a014d9865fd4705acb501ceb9e98[...]
go: downloading github.com/aws/aws-sdk-go-v2 v1.16.16
go: downloading github.com/aws/aws-sdk-go-v2/config v1.17.8
go: downloading github.com/aws/aws-sdk-go-v2/credentials v1.12.21
go: downloading github.com/aws/aws-sdk-go-v2/service/ecr v1.17.18
go: downloading github.com/aws/smithy-go v1.13.3
go: downloading github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.12.17
go: downloading github.com/aws/aws-sdk-go-v2/internal/ini v1.3.2[4](...#step:8:4)
go: downloading github.com/aws/aws-sdk-go-v2/service/sso v1.11.23
go: downloading github.com/aws/aws-sdk-go-v2/service/ssooidc v1.13.[6](...#step:8:6)
go: downloading github.com/aws/aws-sdk-go-v2/service/sts v1.16.19
go: downloading github.com/aws/aws-sdk-go-v2/internal/configsources v1.1.23
go: downloading github.com/jmespath/go-jmespath v0.4.0
go: downloading github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.9.1[7](...#step:8:7)
go: downloading github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.4.17
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x[8](...#step:8:8) pc=0x708ae2]
goroutine 1 [running]:
main.checkImageExists(0xc00003d8b0?, 0xc00003d8e0, 0xc00003d8f0)
	/app/ecr.go:63 +0x222
main.main()
	/app/ecr.go:27 +0x[18](.../actions/runs/3847553635/jobs/6554202873#step:8:19)6
exit status 2
```

**Comment by xiongchiamiov** [comment]
We also started getting this, but only on January 19th (reliably working before then, reliably not working after then).  There weren't any code changes made at the time as far as I can tell.

**Comment by xiongchiamiov** [comment]
Ah, ok, some `dlv`ing later and I found out the problem:  the program currently crashes if it runs into an untagged image.  I'll open a pr to fix it.

**Comment by mnmandahalf** [comment]
@lusorio Thank you for your report.
This is fixed in https://github.com/mnmandahalf/check-ecr-image-exists/pull/4 and released in https://github.com/mnmandahalf/check-ecr-image-exists/releases/tag/v0.1.5 .
